services:
  db:
    container_name: postgresql
    image: postgres:18
    environment:
        POSTGRES_USER: briskula
        POSTGRES_PASSWORD: password
    volumes:
      # https://hub.docker.com/_/postgres#pgdata
        - ./volumes/db:/var/lib/postgresql
    ports:
      - 5432:5432